### ISSUE TITLE
How was the data1.raw.bin file generated?

### ISSUE THREAD

**Issue by 909ma** [RangineniBalaji/Heart-rate-and-Breath-rate-estimation-using-Infenon-Radar#1]
Hello. I have a question regarding your project in order to reproduce it.
I am currently using Infineon DEMO BGT60TR13C.
How was the data1.raw.bin file generated?

If the results were obtained using a different radar sensor, would you be willing to upload the bin file so that even with a different radar, I could generate the same file?
Thank you for your project.

**Comment by 909ma** [comment]
Upon further investigation, I've found that with the upgrade of the Fusion GUI version, the option to export to raw.bin format has been removed.



[Recording of Raw ADC Data
The recording of raw ADC data format now standardizes to the ifxdaq recording format for FMCW 60GHz Sensors. Raw data is stored in standard .npy format, and meta-data and sensor configs are stored in a separate JSON format. The GUI offers playback of legacy recordings, but any recording from the GUI will be in the new format. A converter in the Recording menu is available to convert legacy recordings to the new format.](https://community.infineon.com/t5/Radar-sensor/Release-Announcement-Radar-Development-Kit-3-5-1-available-for-download/td-p/622115)

Indeed, with the new version, people may encounter the same issue of not being able to generate raw.bin files.

**Comment by RangineniBalaji** [comment]
> Upon further investigation, I've found that with the upgrade of the Fusion GUI version, the option to export to raw.bin format has been removed.
> 
> [Recording of Raw ADC Data The recording of raw ADC data format now standardizes to the ifxdaq recording format for FMCW 60GHz Sensors. Raw data is stored in standard .npy format, and meta-data and sensor configs are stored in a separate JSON format. The GUI offers playback of legacy recordings, but any recording from the GUI will be in the new format. A converter in the Recording menu is available to convert legacy recordings to the new format.](https://community.infineon.com/t5/Radar-sensor/Release-Announcement-Radar-Development-Kit-3-5-1-available-for-download/td-p/622115)
> 
> Indeed, with the new version, people may encounter the same issue of not being able to generate raw.bin files.

**Comment by RangineniBalaji** [comment]
> > Upon further investigation, I've found that with the upgrade of the Fusion GUI version, the option to export to raw.bin format has been removed.
> > [Recording of Raw ADC Data The recording of raw ADC data format now standardizes to the ifxdaq recording format for FMCW 60GHz Sensors. Raw data is stored in standard .npy format, and meta-data and sensor configs are stored in a separate JSON format. The GUI offers playback of legacy recordings, but any recording from the GUI will be in the new format. A converter in the Recording menu is available to convert legacy recordings to the new format.](https://community.infineon.com/t5/Radar-sensor/Release-Announcement-Radar-Development-Kit-3-5-1-available-for-download/td-p/622115)
> > Indeed, with the new version, people may encounter the same issue of not being able to generate raw.bin files.

Use the Old Version to record the data in bin file
or make appropriate changes in code to accept another files. Provide the Data about the type of file and time you recorded around to get any further insights.
Thank You!
